### ISSUE TITLE
windows. problem with generating key.

### ISSUE THREAD

**Issue by pyur** [skoerfgen/CertLE#12]
when run 'genrsa', on windows, the result is empty.
after investigation i realized that function 'openssl_pkey_export' MUST be supplyed with '$configargs' parameter.
please change:
openssl_pkey_export($key,$pem);
with:
openssl_pkey_export($key, $pem, null, $config);
and also, it will be good to check result code of 'openssl_pkey_export', and throw exception.

**Comment by tag6** [comment]
Thank you, works fine. Hope it gets accepted soon.

**Comment by skoerfgen** [comment]
@pyur Thank you for reporting this issue! I have changed the code and also added a check to `openssl_pkey_new` and `openssl_pkey_export`
