### ISSUE TITLE
domain_key.pem how can i get it?

### ISSUE THREAD

**Issue by spiceword** [skoerfgen/CertLE#16]
when i execute ...
./certle cert account_key.pem domain_key.pem \
	-w /var/www/example.com/ \
	-d example.com \
	-d www.example.com \
	--csr csr.pem \
	--cert cert.pem \
	--chain chain.pem \
	--fullchain fullchain.pem

BUT!  domain_key.pem?!  how can i get it? how to get ?
Generating Certificate Signing Request (CSR)...Error: Could not load domain key: domain_key.pem
error:02001002:system library:fopen:No such file or directory

**Comment by nblom** [comment]
./certle genrsa 4096 > domain_key.pem

Not an issue with code, please close issue.
