### ISSUE TITLE
why not support 302?

### ISSUE THREAD

**Issue by spiceword** [skoerfgen/CertLE#18]
in source code  LE.inc.php line 140:
list(,$code,$status)=explode(' ',reset($http_response_header),3);
if($code[0]!='2')  throw Exception;

why not support 302 ?
when http 302 , $http_response_header like this:
array(23) {
  [0]=>
  string(18) "HTTP/1.1 302 FOUND"
  [1]=>
  string(17) "Connection: close"
  [2]=>
  string(22) "Server: meinheld/0.6.1"
  [3]=>
  string(35) "Date: Tue, 06 Feb 2018 11:21:21 GMT"
  [4]=>
  string(38) "Content-Type: text/html; charset=utf-8"
  [5]=>
  string(17) "Content-Length: 0"
  [6]=>
  string(30) "Location: https://httpbin.org/"
  [7]=>
  string(30) "Access-Control-Allow-Origin: *"
  [8]=>
  string(38) "Access-Control-Allow-Credentials: true"
  [9]=>
  string(19) "X-Powered-By: Flask"
  [10]=>
  string(34) "X-Processed-Time: 0.00107908248901"
  [11]=>
  string(14) "Via: 1.1 vegur"
  [12]=>
  string(15) "HTTP/1.1 200 OK"
  [13]=>
  string(17) "Connection: close"
  [14]=>
  string(22) "Server: meinheld/0.6.1"
  [15]=>
  string(35) "Date: Tue, 06 Feb 2018 11:21:21 GMT"
  [16]=>
  string(38) "Content-Type: text/html; charset=utf-8"
  [17]=>
  string(21) "Content-Length: 13011"
  [18]=>
  string(30) "Access-Control-Allow-Origin: *"
  [19]=>
  string(38) "Access-Control-Allow-Credentials: true"
  [20]=>
  string(19) "X-Powered-By: Flask"
  [21]=>
  string(34) "X-Processed-Time: 0.00848388671875"
  [22]=>
  string(14) "Via: 1.1 vegur"
}

but this is ok!  not Exception!

**Comment by nblom** [comment]
302 is redirect, not an locally served file. You cant redirect the validation for letsencrypt to some other server for validation, it needs to be local. The process requires a 2xx code to proceed.
Also, note that the issue tracker is not for support. For support or help, please ask in letsencrypt forum.

**Comment by skoerfgen** [comment]
@spiceword Thanks for reporting this issue! I have updated the code to be able to handle redirects now, just get the newest version :)

@nblom Redirects are supported: https://community.letsencrypt.org/t/webroot-http-01-validation-is-ok-with-redirects-to-https/50879
