### ISSUE TITLE
Fail on register account

### ISSUE THREAD

**Issue by gobr4ga** [skoerfgen/CertLE#3]
Hello,

When I use the command

`./certle register hostmaster_example_com.pem hostmaster@example.com`

show this message

```
Error: request error: https://acme-v01.api.letsencrypt.org/directory
file_get_contents(https://acme-v01.api.letsencrypt.org/directory): failed to open stream: operation failed
```

PHP 7.0.12 on macOS

**Comment by skoerfgen** [comment]
do you have the PHP OpenSSL Extension installed? (it is required)

you could check this by running the following code snippet:

```
<?php

var_dump(extension_loaded('openssl'));

```

(i should probably add this check to CertLE anyway..)

**Comment by gobr4ga** [comment]
returned

`bool(true)`

![screen shot 2016-12-14 at 17 51 58](https://cloud.githubusercontent.com/assets/16680429/21198342/1aae7e92-c226-11e6-8964-ca43ceb40718.png)

**Comment by skoerfgen** [comment]
do you get any errors/warnings when running this code:

```
<?php

error_reporting(E_ALL);

$ctx=stream_context_create(array(
	'ssl'=>array(
		'verify_peer'=>true
	)
));

echo file_get_contents('https://acme-v01.api.letsencrypt.org/directory',false,$ctx);
```


if yes, change 'verify_peer' from true to false and try again, does it then work?

**Comment by gobr4ga** [comment]
Returned:

```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /Users/diogo/Sites/labs/php/ssl_certificates/CertLE-master/teste.php on line 11

Warning: file_get_contents(): Failed to enable crypto in /Users/diogo/Sites/labs/php/ssl_certificates/CertLE-master/teste.php on line 11

Warning: file_get_contents(https://acme-v01.api.letsencrypt.org/directory): failed to open stream: operation failed in /Users/diogo/Sites/labs/php/ssl_certificates/CertLE-master/teste.php on line 11
```

Then I changed the value of verify_peer to false, returned:

`{ "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change", "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz", "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert", "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg", "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert" }`

**Comment by gobr4ga** [comment]
I'm testing on a local machine. From what I realized, to generate the certificate for a domain, I need to run on the server where the domain is hosted, right?

**Comment by skoerfgen** [comment]
in this case it's obvious what's wrong, if verify_peer is true (which is default) php tries to verify the chain of trust (https://en.wikipedia.org/wiki/Chain_of_trust) of the https connection

let's encrypt uses the following chain of trust:

![image](https://cloud.githubusercontent.com/assets/17513412/21275780/aa8dc32a-c3ce-11e6-9548-9365d09af57a.png)

"DST Root CA X3" is the root certificate here, which has to be installed on your operating system, which is obviously not the case, so you get the 'certificate verify failed' and 'Failed to enable crypto' openssl errors

with verify_peer set to false you got the expected response, so to solve the problem you would have to add the "DST Root CA X3" certificate to the list of trusted certificates of the operating system. Here is "DST Root CA X3":

```
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----
```

side note:
you can determine where the certificates are located on your system by running the following code:

```
<?php

	print_r(openssl_get_cert_locations());
```

**Comment by skoerfgen** [comment]
> I'm testing on a local machine. From what I realized, to generate the certificate for a domain, I need to run on the server where the domain is hosted, right?


basically certle was designed to be run on the same machine where the webserver is running since it has to place a challenge file into the DocumentRoot for the domain which then gets fetched by let's encrypt to complete the verification process.


but technically it's not required to be run on the same machine, you could for example mount the webservers DocumentRoot for the domain remotely to your machine.

if you - for example - mounted the DocumentRoot of your domain to your local folder /mnt/www, you could run it locally:


```
./certle cert account_key.pem domain_key.pem \
    -w /mnt/www/ \
    -d example.com \
    --csr csr.pem \
    --cert cert.pem \
    --chain chain.pem \
    --fullchain fullchain.pem
```
