### ISSUE TITLE
Creating domain_key.pem

### ISSUE THREAD

**Issue by bilogic** [skoerfgen/CertLE#5]
Hi,

Is there a way to generate a domain_key.pem using CertLE? Thank you.

**Comment by skoerfgen** [comment]
yes, you can use: (for example)

    ./certle genrsa 4096 > domain_key.pem

to generate it.

it's equivalent to:

    openssl genrsa 4096 > domain_key.pem

**Comment by dansalahi** [comment]
Hi
PHP Notice:  tempnam(): file created in the system's temporary directory in C:\xampp\htdocs\CertLE-master\CertLE.php on line 60 
i have this error in the windows.
 I use  `php certle.php genrsa 4096 > domain_key.pem`

**Comment by skoerfgen** [comment]
@m-salahi 

Hi!

Thanks for the bug report!
I updated CertLE, so the problem should not occur anymore.

(This error message is a new feature since PHP 7 -> https://bugs.php.net/bug.php?id=69489)
