### ISSUE TITLE
Windows Server 2003 compatibility

### ISSUE THREAD

**Issue by SierraSue** [skoerfgen/CertLE#6]
I have made some minor modifications to make this scripts compatible with PHP 5.4 on Windows as this seems to be the only client capable of running on pre-historical **Windows Server 2003**.

I can post it somewhere, if anyone is interested.

**Comment by skoerfgen** [comment]
Maybe  @tkauppin is interested: https://github.com/skoerfgen/CertLE/issues/7

**Comment by skoerfgen** [comment]
#7
