### ISSUE TITLE
PHP 5.4.x compatibility

### ISSUE THREAD

**Issue by tkauppin** [skoerfgen/CertLE#7]
"Finally" is supported only in 5.5 or later versions.
Can be also some other incompatibilities.

Someone might ask why I'm trying to use such an old PHP version but this time I have no other option..

**Comment by skoerfgen** [comment]
As far as I can tell (have not tested it) it should work on PHP >=5.4.8, since
there is a constant used in the code "OPENSSL_ALGO_SHA256", which was added in
PHP 5.4.8. And this is the most "modern" PHP feature used in the code I can think of.


This could also be interesting: #6
